In [2]:
# sempre a primeira célula do notebook, importar o que você vai usar.
# Se aparecer erro aqui, a bibliotca não está instalada, ou o kernel do notebook não é o mesmo do ambiente onde a biblioteca foi instalada.
# Solução: abra o terminal e rode pip install pandas openpyxl

import pandas as pd #biblioteca para manipulação de dados
import re #biblioteca para expressões regulares, usada para extrair o número do nome do arquivo
from datetime import datetime #biblioteca para manipulação de datas, usada para extrair o mês do nome do arquivo

#confirmar que as importações funcionaram, rodando a célula. Se não aparecer erro, deu certo.

print(' pandas versão', pd.__version__ ) #imprime a versão do pandas para confirmar que está instalado
print(' bibliotecas importadas com sucesso') #mensagem de confirmação

 pandas versão 3.0.2
 bibliotecas importadas com sucesso

In [4]:
#pd.read_csv() #para ler o arquivo em csv
#Caminho é onde está o arquivo, como ele está na mesma pasta do notebook, só preciso colocar o nome do arquivo

caminho = r"C:\Users\Stefano\Documents\SC TEC\aula 4\turma-visualizacao-de-dados\alunos\stefano_laurito\semana_04\base_rh.csv" #caminho do arquivo, se o arquivo estiver na mesma pasta do notebook, só precisa colocar o nome do arquivo
df = pd.read_csv(
    caminho,
    sep=';',
    encoding='cp1252',
    decimal=','
    ) 

print('arquivo lido com sucesso!') #mensagem de confirmação
print(f' total de linhas: {df.shape[0]}') #imprime o número de linhas do dataframe
print(f' total de colunas: {df.shape[1]}') #imprime o número de colunas do dataframe

arquivo lido com sucesso!
 total de linhas: 1000
 total de colunas: 10

In [5]:
#df.head() #mostra as primeiras 5 linhas do dataframe, para confirmar que os dados foram lidos corretamente
#Padrão: df.head() mostra as primeiras 5 linhas, df.head(10) mostra as primeiras 10 linhas, df.head(-1) mostra todas as linhas menos a última, df.head(0) mostra apenas o cabeçalho, sem nenhuma linha de dados.
# Use para ter uma rápida visão geral dos dados, para confirmar que foram lidos corretamente, e para entender a estrutura do dataframe. 
df.head(5) #mostra as primeiras 5 linhas do dataframe, para confirmar que os dados foram lidos corretamente

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
0,1,Julia Nunes,Logística,Coordenador,9088.34,13/08/2024,F,43,Solteiro,Inativo
1,2,Sr. Gustavo Duarte,TI,Gerente,8155.98,29/04/2017,F,59,Solteiro,Inativo
2,3,Srta. Mariana Cunha,RH,Coordenador,14027.93,11/12/2024,F,27,Divorciado,Ativo
3,4,Ana Sophia da Cruz,Produção,Técnico,6647.97,16/06/2019,M,50,Casado,Inativo
4,5,Dr. Nicolas Pinto,Produção,Gerente,8730.19,29/03/2019,F,62,Casado,Inativo

In [6]:
#df.tail() #mostra as últimas 5 linhas do dataframe, para confirmar que os dados foram lidos corretamente
#serve para ter uma rápida visão geral dos dados, para confirmar que foram lidos corretamente, e para entender a estrutura do dataframe.
# se o arquivo tiver muitas linhas, pode ser útil para confirmar que o final do arquivo também foi lido corretamente, e para entender a estrutura do dataframe.
df.tail(5) #mostra as últimas 5 linhas do dataframe, para confirmar que os dados foram lidos corretamente

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
995,996,Matheus Aragão,Financeiro,Analista,11389.03,06/05/2022,F,26,Viúvo,Ativo
996,997,Ryan Martins,Financeiro,Analista,14060.42,05/06/2023,F,37,Viúvo,Ativo
997,998,Isabelly Ferreira,TI,Gerente,2348.73,29/12/2023,F,58,Solteiro,Inativo
998,999,Thales Farias,Produção,Analista,9430.62,25/12/2019,M,41,Solteiro,Ativo
999,1000,Sra. Maysa Costela,Produção,Técnico,12549.72,14/11/2022,M,46,Viúvo,Inativo

In [7]:
#df.columns #mostra os nomes das colunas do dataframe, para confirmar que os dados foram lidos corretamente, e para entender a estrutura do dataframe.
#.tolist() #converte o index do dataframe em uma lista, para facilitar a manipulação dos nomes das colunas.

print('Colunas do dataset:', df.columns.tolist()) #mostra os nomes das colunas do dataframe, para confirmar que os dados foram lidos corretamente, e para entender a estrutura do dataframe.

Colunas do dataset: ['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status']

In [8]:
#diagnostico: tipos e nulos
#dt.info() #mostra o tipo de cada coluna, e quantos valores nulos tem em cada coluna, para confirmar que os dados foram lidos corretamente, e para entender a estrutura do dataframe.
#nome de cada coluna
#tipo de cada coluna
#quantidade de valores não nulos em cada coluna
#quantidade de valores nulos em cada coluna (total de linhas - quantidade de valores não
#nulos)
df.info() #mostra o tipo de cada coluna, e quantos valores nulos tem em cada coluna, para confirmar que os dados foram lidos corretamente, e para entender a estrutura do dataframe.

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   str
 2   Departamento    1000 non-null   str
 3   Cargo           1000 non-null   str
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   str
 6   Genero          1000 non-null   str
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   str
 9   Status          1000 non-null   str
dtypes: float64(1), int64(2), str(7)
memory usage: 78.3 KB

In [10]:
#dt.isnull() cria um dataframe booleano, com True para cada valor nulo, e False para cada valor não nulo. dt.isnull().sum() soma os valores booleanos, contando quantos valores nulos tem em cada coluna.
#.sum() soma os valores booleanos, contando quantos valores nulos tem em cada coluna.
#resultado: quantidade de valores nulos em cada coluna, para confirmar que os dados foram lidos corretamente, e para entender a estrutura do dataframe.
print('Quantidade de valores nulos em cada coluna:\n', df.isnull().sum()) #quantidade de valores nulos em cada coluna, para confirmar que os dados foram lidos corretamente, e para entender a estrutura do dataframe.

#percentual de nulo - mais util para entender a proporção de nulos em cada coluna, especialmente se o número total de linhas for grande. df.isnull().mean() calcula a média dos valores booleanos, dando a proporção de valores nulos em cada coluna.
# len(df) #número total de linhas do dataframe, usado para calcular o percentual de nulos.
#resultado: percentual de valores nulos em cada coluna, para confirmar que os dados foram lidos corretamente, e para entender a estrutura do dataframe.
print('Percentual de valores nulos em cada coluna:\n', df.isnull().mean()) #percentual de valores nulos em cada coluna, para confirmar que os dados foram lidos corretamente, e para entender a estrutura do dataframe.

Quantidade de valores nulos em cada coluna:
 ID_Funcionario    0
Nome              0
Departamento      0
Cargo             0
Salario           0
Data_Admissao     0
Genero            0
Idade             0
Estado_Civil      0
Status            0
dtype: int64
Percentual de valores nulos em cada coluna:
 ID_Funcionario    0.0
Nome              0.0
Departamento      0.0
Cargo             0.0
Salario           0.0
Data_Admissao     0.0
Genero            0.0
Idade             0.0
Estado_Civil      0.0
Status            0.0
dtype: float64

In [12]:
df.describe().round(2) #mostra estatísticas descritivas das colunas numéricas do dataframe, para entender a distribuição dos dados, e para confirmar que os dados foram lidos corretamente. round() arredonda os valores para facilitar a leitura.

       ID_Funcionario   Salario    Idade
count         1000.00   1000.00  1000.00
mean           500.50   8579.95    41.40
std            288.82   3657.37    13.67
min              1.00   2000.71    18.00
25%            250.75   5564.54    30.00
50%            500.50   8571.13    41.00
75%            750.25  11554.63    53.00
max           1000.00  14954.51    65.00

In [14]:
#nunique() mostra o número de valores únicos em cada coluna, para entender a diversidade dos dados, e para confirmar que os dados foram lidos corretamente.
print('Número de valores únicos em cada coluna:\n', df.nunique()) #número de valores únicos em cada coluna, para entender a diversidade dos dados, e para confirmar que os dados foram lidos corretamente.

Número de valores únicos em cada coluna:
 ID_Funcionario    1000
Nome               976
Departamento         6
Cargo                5
Salario           1000
Data_Admissao      878
Genero               2
Idade               48
Estado_Civil         4
Status               2
dtype: int64

In [16]:
#df['coluna'].value_counts() #mostra a contagem de cada valor único na coluna, para entender a distribuição dos dados, e para confirmar que os dados foram lidos corretamente. Útil para colunas categóricas.
#resultado: contagem de cada valor único na coluna, para entender a distribuição dos dados, e para confirmar que os dados foram lidos corretamente. Útil para colunas categóricas.
#print('Contagem de cada valor único na coluna "coluna":\n', df['coluna'].value_counts()) #mostra a contagem de cada valor único na coluna, para entender a distribuição dos dados, e para confirmar que os dados foram lidos corretamente. Útil para colunas categóricas. Substitua 'coluna' pelo nome da coluna que você quer analisar.

#for col in df.columns: #loop para mostrar a contagem de cada valor único em cada coluna, para entender a distribuição dos dados, e para confirmar que os dados foram lidos corretamente. Útil para colunas categóricas.
#    print(f'Contagem de cada valor único na coluna "{col}":\n', df[col].value_counts()) #mostra a contagem de cada valor único na coluna, para entender a distribuição dos dados, e para confirmar que os dados foram lidos corretamente. Útil para colunas categóricas. Substitua 'coluna' pelo nome da coluna que você quer analisar.

In [19]:
#seleção de coluna -> df['nome']
#seleção de várias colunas -> df[['nome1', 'nome2']]
#filtro de linha -> df[df['coluna'] == 'valor']

df['Departamento'].head(3)

0    Logística
1           TI
2           RH
Name: Departamento, dtype: str

In [22]:
df[['Departamento', 'Cargo', 'Salario']].head(6)

  Departamento        Cargo   Salario
0    Logística  Coordenador   9088.34
1           TI      Gerente   8155.98
2           RH  Coordenador  14027.93
3     Produção      Técnico   6647.97
4     Produção      Gerente   8730.19
5           RH     Analista  12403.42

In [ ]:
#filtro simples: df[df['Status'] == 'Ativo'] #filtra as linhas onde a coluna "Status" é igual a "Ativo", mostrando apenas os funcionários ativos.

print(f'Total de funcionários: {len(df)}') #imprime o número total de funcionários, contando as linhas do dataframe
print(f'funcionários ativos: {len(df[df["Status"] == "Ativo"])}') #imprime o número de funcionários ativos, filtrando as linhas do dataframe onde a coluna "Status" é igual a "Ativo"
print(f'funcionários inativos: {len(df[df["Status"] == "Inativo"])}') #imprime o número de funcionários inativos, filtrando as linhas do dataframe onde a coluna "Status" é igual a "Inativo"

Total de funcionários: 1000
funcionários ativos: 515
funcionários inativos: 485

In [24]:
#filtro composto: df[(df['Status'] == 'Ativo') & (df['Departamento'] == 'Vendas')] #filtra as linhas onde a coluna "Status" é igual a "Ativo" e a coluna "Departamento" é igual a "Vendas", mostrando apenas os funcionários ativos do departamento de vendas. Use & para "e", | para "ou", e ~ para "não". Lembre-se de colocar cada condição entre parênteses.

#use & para "e", | para "ou", e ~ para "não". Lembre-se de colocar cada condição entre parênteses. Exemplo: df[(df['Status'] == 'Ativo') & (df['Departamento'] == 'Vendas')] #filtra as linhas onde a coluna "Status" é igual a "Ativo" e a coluna "Departamento" é igual a "Vendas", mostrando apenas os funcionários ativos do departamento de vendas.

gerentes_ti = df[(df['Cargo'] == 'Gerente') & (df['Departamento'] == 'TI')] #filtra as linhas onde a coluna "Cargo" é igual a "Gerente" e a coluna "Departamento" é igual a "TI", mostrando apenas os gerentes do departamento de TI.
print(f'Número de gerentes de TI: {len(gerentes_ti)}') #imprime o número de gerentes de TI, contando as linhas do dataframe filtrado. Substitua 'Cargo' e 'Departamento' pelos nomes das colunas que você quer filtrar, e 'Gerente' e 'TI' pelos valores que você quer filtrar. 
gerentes_ti[['Nome', 'Salario','Status']] #mostra as colunas "Nome" e "Salario" do dataframe filtrado, para ver os nomes e salários dos gerentes de TI. Substitua 'Nome' e 'Salario' pelos nomes das colunas que você quer mostrar.

Número de gerentes de TI: 31

                            Nome   Salario   Status
1             Sr. Gustavo Duarte   8155.98  Inativo
49             Benjamin da Costa   9766.01  Inativo
130             Catarina Costela   9597.83  Inativo
131                Laura Cardoso   7364.46  Inativo
175                Maria Cardoso  12127.27  Inativo
187            Ana Júlia Cardoso   8738.63    Ativo
247                  Ian Pereira   2395.32    Ativo
273            Ana Clara Peixoto   7301.14    Ativo
296               Augusto Santos   8237.80  Inativo
307              Manuela Barbosa   7015.91    Ativo
323             Antônio Oliveira   5273.24    Ativo
393          Luiz Gustavo da Luz   2543.19  Inativo
414                 Stella Costa  11718.30    Ativo
422                Bryan da Cruz  11790.21    Ativo
426               Emilly Freitas   5147.62  Inativo
463            Brenda Nascimento   5429.24    Ativo
493                  Sofia Sales   4941.24  Inativo
533              Manuela Cardoso   5305.96  Inativo
607          Luiz Henrique Souza   4398.17    Ativo
634               Bruna da Cunha   3423.93  Inativo
650                 Alícia Porto   9547.18  Inativo
676               Bianca da Cruz   7903.06  Inativo
691  Sra. Maria Fernanda Freitas   2686.67    Ativo
707              Emanuelly Souza   8305.81  Inativo
724                Olivia Moraes   3124.24  Inativo
841                Bernardo Lima   6149.05    Ativo
886         Sra. Caroline Araújo   6750.44  Inativo
891            Ana Clara Moreira  14523.10    Ativo
909                  Luna Novaes   3106.49  Inativo
927            Valentina Cardoso  10602.13    Ativo
997            Isabelly Ferreira   2348.73  Inativo

In [27]:
#Estátiticas rapidas de uma coluna numérica: df['coluna'].mean(), df['coluna'].median(), df['coluna'].min(), df['coluna'].max(), df['coluna'].std() #mostra a média, mediana, mínimo, máximo, e desvio padrão da coluna, para entender a distribuição dos dados, e para confirmar que os dados foram lidos corretamente. Substitua 'coluna' pelo nome da coluna que você quer analisar.
#mean() mostra a média da coluna, para entender a distribuição dos dados, e para confirmar que os dados foram lidos corretamente. Substitua 'coluna' pelo nome da coluna que você quer analisar.
#max() mostra o valor máximo da coluna, para entender a distribuição dos dados, e para confirmar que os dados foram lidos corretamente. Substitua 'coluna' pelo nome da coluna que você quer analisar.
#min() mostra o valor mínimo da coluna, para entender a distribuição dos dados, e para confirmar que os dados foram lidos corretamente. Substitua 'coluna' pelo nome da coluna que você quer analisar.
#mediana() mostra a mediana da coluna, para entender a distribuição dos dados, e para confirmar que os dados foram lidos corretamente. Substitua 'coluna' pelo nome da coluna que você quer analisar.
                             
print(f'Média do salário: {df["Salario"].mean():.2f}')
print(f'Máximo do salário: {df["Salario"].max():.2f}')
print(f'Mínimo do salário: {df["Salario"].min():.2f}')
print(f'Mediana do salário: {df["Salario"].median():.2f}')

Média do salário: 8579.95
Máximo do salário: 14954.51
Mínimo do salário: 2000.71
Mediana do salário: 8571.13