In [77]:
import pandas as pd

In [78]:
# importando a base de dados e modificando os tipos de dados para o ideal em cada coluna.

df  = pd.read_csv('Base Varejo.csv', sep=';', dtype= {'CO_ID':str,'CL_ID':str,'CL_GENERO':'category','CL_FHL':str,'CL_SEG':'category','PR_ID':str,'PR_CAT':'category'})

# alterando o formota da coluna 'DATA', pois estava no formato m%/%d/%Y

df['DATA'] = pd.to_datetime(df['DATA'], format='%d/%m/%Y')

df_copy = df.copy()

In [79]:
# recolhendo amostras
df_copy.sample(10)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
194417,2019-12-24,218767,447,M,2,0,B,189,ALIMENTOS,GRANOLA,NaN,NaN,NaN,NaN
803240,2022-07-16,891674,364,F,4,2,C,50,ALIMENTOS,PAO DE FORMA,NaN,NaN,NaN,NaN
18062,2019-06-02,21095,326,F,1,0,B,216,ALIMENTOS,BROCOLIS,NaN,NaN,NaN,NaN
193962,2019-12-18,218216,66,M,3,3,B,26,ALIMENTOS,COXA E SOBRECOXA DE FRANGO,NaN,NaN,NaN,NaN
237288,2020-07-03,263241,409,F,3,4,B,38,ALIMENTOS,LEITE CONDENSADO,NaN,NaN,NaN,NaN
324357,2020-07-26,359999,486,M,4,0,B,81,HIGIENE,HIDRATANTE,NaN,NaN,NaN,NaN
549559,2021-03-07,605677,15,M,2,1,C,111,LIMPEZA,SABAO EM PO,NaN,NaN,NaN,NaN
472267,2021-03-16,519225,512,M,4,0,B,92,HIGIENE,TINTURAS,NaN,NaN,NaN,NaN
284218,2020-08-05,315060,625,F,4,0,C,53,ALIMENTOS,PRESUNTO COZIDO,NaN,NaN,NaN,NaN
797834,2022-07-13,885773,784,F,1,3,B,30,ALIMENTOS,FILE DE PEIXE,NaN,NaN,NaN,NaN

In [80]:
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  datetime64[us]
 1   CO_ID        830000 non-null  str
 2   CL_ID        830000 non-null  str
 3   CL_GENERO    830000 non-null  category
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  str
 6   CL_SEG       830000 non-null  category
 7   PR_ID        830000 non-null  str
 8   PR_CAT       830000 non-null  category
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: category(3), datetime64[us](1), float64(4), int64(1), str(5)
memory usage: 72.0 MB

In [81]:
# removendo colunas inteiramente vazias:
df_copy = df_copy.drop(columns= ['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13'])

In [94]:
# Filtra apenas colunas de texto (object) e categorias (category)
df_copy.describe(include=['object', 'category', 'str'])

,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
count,830000,830000,830000,830000,830000,830000,830000,830000,830000
unique,18471,1000,2,5,5,3,229,7,118
top,2224,822,F,Separado,0,B,93,ALIMENTOS,PRESUNTO COZIDO
freq,89,1777,432576,213742,435501,530163,3773,434767,14381

In [82]:
df_copy.isna().sum()

DATA         0
CO_ID        0
CL_ID        0
CL_GENERO    0
CL_EC        0
CL_FHL       0
CL_SEG       0
PR_ID        0
PR_CAT       0
PR_NOME      0
dtype: int64

In [83]:
# modificando o estado civil para estar condizente com a documentaçao e as regras de negocio da empresa:

map_df = {1:'Casado/União Estável', 2:'Divorciado', 3:'Separado', 4:'Solteiro', 5:'Viuvo'}
df_copy['CL_EC'] = df_copy['CL_EC'].map(map_df)

In [84]:
df_copy.sample(2)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
736965,2022-04-17,820185,817,M,Separado,0,B,66,BEBIDAS,REFRIGERANTE COLA
391966,2020-11-18,431501,317,M,Separado,0,B,141,BEBIDAS,REFRIGERANTE LIMaO

In [85]:
print(df_copy['PR_NOME'].unique())

<StringArray>
[      'REFRIGERANTE GUARANA',        'REFRIGERANTE OUTROS',
            'LENCO UMEDECIDO',                    'ABACAXI',
          'LIMPADOR MULTIUSO',           'HASTES FLEXIVEIS',
                  'MORTADELA',                     'AZEITE',
                  'AMACIANTE',                 'ENERGETICO',
 ...
                  'HAMBUGUER',      'ALIMENTO PARA PASSARO',
                     'CEBOLA',           'ENXAGUANTE BUCAL',
                      'MANGA', 'COXA E SOBRECOXA DE FRANGO',
                    'ABACATE',                      'ARROZ',
                 'ABSORVENTE',             'MOLHO BARBECUE']
Length: 118, dtype: str

In [86]:
# Veja quantas linhas têm #N/D
df_copy[df_copy['PR_CAT'] == '#N/D'].shape[0]

3650

In [87]:
# Veja o nome dos produtos que estão sem categoria
df_copy[df_copy['PR_CAT'] == '#N/D']['PR_NOME'].unique()

<StringArray>
['#N/D']
Length: 1, dtype: str

In [88]:
# print(df['DATA'].unique())
df_copy.duplicated().sum()

np.int64(96553)

In [89]:
# 1. Descobrir quais são os Códigos de Produto (PR_ID) das linhas problemáticas
ids_com_erro = df_copy[df_copy['PR_CAT'] == '#N/D']['PR_ID'].unique()
print(f"Códigos (PR_ID) que deram erro: {ids_com_erro}")

# 2. Verificar se esses mesmos IDs existem no resto da base com os nomes corretos
# Filtramos a base onde a categoria NÃO é #N/D, mas o ID do produto está na nossa lista de erro
produtos_recuperaveis = df_copy[(df_copy['PR_CAT'] != '#N/D') & (df_copy['PR_ID'].isin(ids_com_erro))]

# 3. Mostrar a lista de produtos que conseguimos desvendar
produtos_recuperaveis[['PR_ID', 'PR_CAT', 'PR_NOME']].drop_duplicates()

Códigos (PR_ID) que deram erro: <StringArray>
['107']
Length: 1, dtype: str

Empty DataFrame
Columns: [PR_ID, PR_CAT, PR_NOME]
Index: []

In [90]:
# verificaçao com precentual de nulos:

print((df_copy.isnull().sum() / len(df_copy) * 100).round(2))

DATA         0.0
CO_ID        0.0
CL_ID        0.0
CL_GENERO    0.0
CL_EC        0.0
CL_FHL       0.0
CL_SEG       0.0
PR_ID        0.0
PR_CAT       0.0
PR_NOME      0.0
dtype: float64