In [1]:
import pandas as pd
import numpy as np

In [2]:
# importando a base de dados e modificando os tipos de dados para o ideal em cada coluna.

df  = pd.read_csv('Base Varejo.csv', sep=';', dtype= {'CO_ID':str,'CL_ID':str,'CL_GENERO':'category','CL_FHL':str,'CL_SEG':'category','PR_ID':str,'PR_CAT':'category'})

# alterando o formata da coluna 'DATA', pois estava no formato m%/%d/%Y

df['DATA'] = pd.to_datetime(df['DATA'], format='%d/%m/%Y')

# criaçao da copia da nossa base de dados

df_copy = df.copy()

In [3]:
# recolhendo amostras
df_copy.sample(10)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
157522,2019-05-10,177153,701,M,3,0,B,199,ALIMENTOS,DOCE,NaN,NaN,NaN,NaN
159944,2019-10-10,180432,108,M,1,0,B,45,ALIMENTOS,MANGA,NaN,NaN,NaN,NaN
274619,2020-04-24,304892,19,F,2,2,C,196,HIGIENE,ESCOVA DE DENTE,NaN,NaN,NaN,NaN
133404,2019-08-30,148992,315,F,3,0,B,62,ALIMENTOS,SNACKS,NaN,NaN,NaN,NaN
210091,2020-01-18,235888,180,M,3,4,B,181,ALIMENTOS,LATA DE MILHO,NaN,NaN,NaN,NaN
763698,2022-05-23,849529,224,M,4,0,B,120,LIMPEZA,VASSOURA,NaN,NaN,NaN,NaN
518383,2021-12-05,570404,719,M,1,0,B,19,ALIMENTOS,CAFE,NaN,NaN,NaN,NaN
797477,2022-07-13,885235,387,M,2,2,B,184,ALIMENTOS,IOGURTE,NaN,NaN,NaN,NaN
501298,2021-04-23,552616,80,F,2,1,C,110,LIMPEZA,SABAO,NaN,NaN,NaN,NaN
532931,2021-06-06,587054,323,M,1,3,B,149,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN

In [4]:
# verificaçao de tipos de dados

df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  datetime64[us]
 1   CO_ID        830000 non-null  str
 2   CL_ID        830000 non-null  str
 3   CL_GENERO    830000 non-null  category
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  str
 6   CL_SEG       830000 non-null  category
 7   PR_ID        830000 non-null  str
 8   PR_CAT       830000 non-null  category
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: category(3), datetime64[us](1), float64(4), int64(1), str(5)
memory usage: 72.0 MB

In [5]:
# removendo colunas inteiramente vazias, pois nao fara sentido ter elas dentro da nossa base de dados que posteriormente sera utilizada por alguem:
df_copy = df_copy.drop(columns= ['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13'])

In [6]:
# correcao de inconssisetncias nas colunas PR_CAT e PR_NOME

df_copy['PR_CAT'] = df_copy['PR_CAT'].str.capitalize()
df_copy['PR_NOME'] = df_copy['PR_NOME'].str.capitalize()

In [7]:
df_copy

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,2019-02-01,1000,534,M,4,1,C,67,Bebidas,Refrigerante guarana
1,2019-02-01,1000,534,M,4,1,C,70,Bebidas,Refrigerante outros
2,2019-02-01,1000,534,M,4,1,C,178,Higiene,Lenco umedecido
3,2019-02-01,1000,534,M,4,1,C,4,Alimentos,Abacaxi
4,2019-02-01,1000,534,M,4,1,C,175,Limpeza,Limpador multiuso
...,...,...,...,...,...,...,...,...,...,...
829995,2022-08-19,919822,155,F,2,0,B,183,Alimentos,Ketchup
829996,2022-08-19,919822,155,F,2,0,B,56,Alimentos,Queijo mussarela
829997,2022-08-19,919822,155,F,2,0,B,227,Alimentos,Arroz
829998,2022-08-19,919822,155,F,2,0,B,214,Alimentos,Cebola
829999,2022-08-19,919822,155,F,2,0,B,59,Alimentos,Salgadinho

In [8]:
# Filtra apenas colunas de texto (object), categorias (category) e texto (strings)
df_copy.describe(include=['object', 'category', 'str'])

,CO_ID,CL_ID,CL_GENERO,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
count,830000,830000,830000,830000,830000,830000,830000,830000
unique,18471,1000,2,5,3,229,7,118
top,2224,822,F,0,B,93,Alimentos,Presunto cozido
freq,89,1777,432576,435501,530163,3773,434767,14381

In [9]:

df_copy.isna().sum()

DATA         0
CO_ID        0
CL_ID        0
CL_GENERO    0
CL_EC        0
CL_FHL       0
CL_SEG       0
PR_ID        0
PR_CAT       0
PR_NOME      0
dtype: int64

In [10]:
# modificando o estado civil para estar condizente com a documentaçao e as regras de negocio da empresa:

map_df = {1:'Casado/Uniao Estavel', 2:'Divorciado', 3:'Separado', 4:'Solteiro', 5:'Viuvo'}
df_copy['CL_EC'] = df_copy['CL_EC'].map(map_df)

In [11]:
df_copy.sample(2)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
1128,2019-02-01,2112,72,F,Divorciado,0,A,5,Alimentos,Achocolatado
249130,2020-03-23,276664,264,F,Solteiro,1,B,201,Limpeza,Desinfetante

In [12]:
print(df_copy['PR_CAT'].unique())

['Bebidas' 'Higiene' 'Alimentos' 'Limpeza' 'Acessorios' 'Pet' '#n/d']

In [13]:
# vendo quantas linhas temos valores nulos/ausentes ou #N/D
df_copy[df_copy['PR_CAT'] == '#N/D'].shape[0]

0

In [14]:
# removendo valores #N/D das colunas PR_CAT e PR_NOME

#removendo a categoria da nossa lista
df_copy['PR_CAT'] = df_copy['PR_CAT'].cat.remove_categories('#N/D')

df_copy['PR_NOME'] = df_copy['PR_NOME'].replace('#N/D', np.nan)

df_copy = df_copy.dropna(subset=['PR_CAT', 'PR_NOME'])


# 4. Verificando o resultado e garantindo que os tipos não foram alterados
print("Quantidade de nulos após limpeza:\n", df_copy[['PR_CAT', 'PR_NOME']].isna().sum())
print("\nTipos das colunas:\n", df_copy[['PR_CAT', 'PR_NOME']].dtypes)

AttributeError: Can only use .cat accessor with a 'category' dtype

In [ ]:
print(df_copy['PR_CAT'].unique())

Removemos os valores nulos apos analisar as colunas PR_CAT, PR_NOME e PR_ID pois com os dados atuais se torna impossivel de recuperar esses 3.228 valores nulos/ausentes, iresmo remover eles pois como sao poucos e nao tem maneira alguma de os recuperar, nao farao falta na nossa base

In [ ]:
# Veja o nome dos produtos que estão sem categoria
df_copy[df_copy['PR_CAT'] == '#N/D']['PR_NOME'].unique()

In [ ]:
df_copy.head()

In [ ]:
# verificaçao de dados unicos para possiveis alteraçoes

print(df['PR_NOME'].unique().tolist())

In [ ]:
# verificando duplicatas

df_copy.duplicated().sum()

In [ ]:
# exibiçao em dataframe, para analisarmos melhor a questao das duplicatas

# filtra a base, mostrando as linhas que possuem copias iguais
duplicatas = df_copy[df_copy.duplicated(keep=False)]

# como queremos descobrir se a questao das duplicatas tem algo haver com o id do cliente e o id do produto as ordemos dessa forma para  que facilite nossa analise
duplicatas.sort_values(by=['CO_ID', 'PR_ID']).head(10)

Apos analisar os indices, descobrimos um padrao, como da para observar, os numeros dos indices estao espaçados, oque provavelmente significa que ao passar no caixa os produtos, eles foram sendo passados de maneira meio espaçada (de acordo com o indice), oque significa que nao foi um erro do sistema, entao a compra dos produtos esta correta, e a questao das linhas duplicadas, atesta que nao ha erro algum, caso apagassemos, iriamos perder uma grande quantidade de dados valiossimos para a empresa em questao

In [ ]:
# apos a analise anterior, decidimos criar uma nova coluna de quantidade, contendo as linhas duplicadas

# coluna = df_copy.columns.tolist()
# df_copy = df_copy.groupby(coluna, dropna=False).size().reset_index(name='QTD_PR')

df_copy[df_copy['PR_ID'] == '107'].head(10)

In [ ]:
df_copy

In [ ]:
# verificaçao com precentual de nulos:

print((df_copy.isnull().sum() / len(df_copy) * 100).round(2))